docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Introduction: intro.md
    - "Quick Start": quick-start.md
    - Reference:
        - "Generating Responses": response.md
        - "Exceptions": exception.md
        - "Error Handling Middleware": middleware.md
        - "Not Found Handler": not-found-handler.md
        - "Default Types": default-types.md
site_name: mezzio-problem-details
site_description: 'Problem Details for PSR-7 HTTP APIs addressing the RFC 7807 standard'
repo_url: 'https://github.com/mezzio/mezzio-problem-details'
extra:
    project: Mezzio
